### ISSUE TITLE
Almost half of tests failing

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/s3-tests#40]
## Current Behavior
106+141 tests failing out of 531:
https://http.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/10-/index.html

## Expected Behavior
Green. Some parts of the API are known to be unsupported:
https://github.com/nspcc-dev/neofs-s3-gw/blob/master/docs/aws_s3_compat.md

While some can be bugs.

## Possible Solution
Suppress unsupported things, create issues for problems in supported cases.

**Comment by evgeniiz321** [comment]
All tests that were without special marks (fails_on_aws/fails_on_dbstore) were analyzed, relevant bugs were opened. For special marks, additional issues were opened.
