### ISSUE TITLE
Update deploy to NeoFS pipeline

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/s3-tests#68]
In the worker pipeline [Publish to NeoFS](https://github.com/nspcc-dev/neofs-s3-gw/actions/runs/9313233368/job/25635329293#step:23:440) a lot of similar messages
```
WARNING: Unsupported extension: attach (file: neofs-test-allure-generated-report/data/attachments/857a3e9d3b24cdf.attach) skipping (supported are: ['svg', 'txt', 'js', 'json', 'csv', 'css', 'html', 'xml', 'htm', 'png', 'jpeg', 'jpg', 'gif', 'mp4', 'avi', 'webm']
```

## Current Behavior
The step log very long

## Expected Behavior
There is no such warnings

**Comment by roman-khimov** [comment]
Looks like Allure thing. @evgeniiz321?

**Comment by evgeniiz321** [comment]
Fixed by https://github.com/nspcc-dev/s3-tests/pull/76/commits/09904a2ca7fcdbaa7e3421331e4d0adab9344bab
