### ISSUE TITLE
Update tests logic, after EACL accounts

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/s3-tests#75]
The start point https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/308-1724050445/index.html#suites/6d7c9ec7c4f3e4460ae14fd266a64e04/88171d41aee11aef/

## Current Behavior
* **test_bucket_acl_grant_email_not_exist** - the test sends old owner data
> ID must be equal to the DisplayName (address)
```
DisplayName = {string} "NNAsHLb7CfTRb1Z8P9GEdb9LW32cik7gPh" // address
ID = {string} "03c70a35741e3b811bec892b982d29c6982b32cffcbb36bd3d286537b2fc6124d6" // public key
```
* **test_bucket_acl_grant_nonexist_user** - uses `_foo` as userID. It is wrong and must be an address. You should replace it with any valid address. For instance: `NNAsHLb7CfTRb1Z8P9GEdb9LW32cik7gPh`

* **test_object_acl_full_control_verify_attributes** - has problems similar to the first one. Wrong value in ID, sends public key

## Possible Solution
I consider, we may find more issues with tests and I would suggest to replace ID with displayName in the init
* https://github.com/nspcc-dev/s3-tests/blob/5813c6433b961244abee6d48879089f2a1e39dd0/s3tests_boto3/functional/__init__.py#L281 for all clients.

**Comment by evgeniiz321** [comment]
Partially fixed by https://github.com/nspcc-dev/s3-tests/pull/76. Regarding test_bucket_acl_grant_nonexist_user - this test intentionally sets invalid userid, s3 gw should handle it more gracefully, than 500 error code. 400 - would be good.

**Comment by roman-khimov** [comment]
It was fixed by https://github.com/nspcc-dev/neofs-s3-gw/pull/983.

**Comment by evgeniiz321** [comment]
good, we have a fully green run - https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/320-1724156123/index.html, closing this issue.
